# Generated by Django 5.2.16 on 2026-08-01 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_rename_website_artist_primary_website_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='name',
        ),
    ]
