# Generated by Django 5.2.16 on 2026-08-01 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_remove_piece_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='artist_uuid',
            new_name='artist',
        ),
    ]
