# Generated by Django 5.2.16 on 2026-08-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_rename_artist_uuid_piece_artist'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_statement',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
