# Generated by Django 5.2.16 on 2026-08-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_artist_artist_statement_artist_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='slug',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='piece',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
