# Generated by Django 5.2.16 on 2026-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_alter_artist_name_alter_artist_slug_alter_piece_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_statement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medium',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='medium',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
