# Generated by Django 5.2.16 on 2026-08-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_alter_artist_artist_statement_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=255, upload_to='artists/profiles/'),
        ),
    ]
