# Generated by Django 5.2.16 on 2026-08-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_alter_artist_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
