# Generated by Django 5.2.16 on 2026-08-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_artist_slug'),
        ('artists', '0010_alter_artist_phone'),
    ]

    operations = [
    ]
