# Generated by Django 5.2.16 on 2026-08-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_merge_0003_alter_artist_slug_0010_alter_artist_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piece',
            name='url',
        ),
        migrations.AddField(
            model_name='piece',
            name='image',
            field=models.ImageField(blank=True, upload_to='artists/pieces/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='artists/profiles/'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
