# Generated by Django 5.2.16 on 2026-08-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_remove_piece_url_piece_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='media/artists/profiles/'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/artists/pieces/'),
        ),
    ]
