# Generated by Django 5.2.15 on 2026-06-04 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('submitter_name', models.CharField(blank=True, max_length=200)),
                ('submitter_email', models.EmailField(blank=True, max_length=254)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('opening_reception_date', models.DateField(blank=True, null=True)),
                ('opening_reception_time', models.TimeField(blank=True, null=True)),
                ('artist_talk_date', models.DateField(blank=True, null=True)),
                ('artist_talk_time', models.TimeField(blank=True, null=True)),
                ('closing_reception_date', models.DateField(blank=True, null=True)),
                ('closing_reception_time', models.TimeField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
