# Generated by Django 5.2.15 on 2026-07-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, choices=[('visual_arts', 'Visual Arts'), ('music', 'Music'), ('theater', 'Theater'), ('dance', 'Dance'), ('museums', 'Museums'), ('other', 'Other')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
