# Generated by Django 5.2.15 on 2026-07-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_category_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, max_length=320, unique=True),
        ),
    ]
