# Generated by Django 5.2.15 on 2026-08-13 01:42

from django.db import migrations, models


def create_default_slider_settings(apps, schema_editor):
    SliderSettings = apps.get_model('events', 'SliderSettings')
    SliderSettings.objects.get_or_create(pk=1, defaults={'interval_seconds': 4})


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider/')),
                ('caption', models.CharField(blank=True, help_text='Optional — e.g. artist name or piece title.', max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='Slides are shown lowest-first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SliderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_seconds', models.PositiveSmallIntegerField(default=4, help_text='How long each slide stays on screen before advancing.')),
            ],
            options={
                'verbose_name': 'Slider settings',
                'verbose_name_plural': 'Slider settings',
            },
        ),
        migrations.RunPython(create_default_slider_settings, migrations.RunPython.noop),
    ]
